name: PHP Composer

on: [push]

jobs:
  build:
    name: PHPUnit Tests (PHP ${{ matrix.php-versions }}, Composer ${{ matrix.composer-versions }} --prefer-${{ matrix.composer-deps }} --prefer-${{ matrix.composer-deps-source }})
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    continue-on-error: ${{ matrix.allow-to-fail }}
    strategy:
      matrix:
        php-versions: ['7.4']
        allow-to-fail: [false]
        composer-versions:
          - composer:v1
        composer-deps:
          - stable
          - lowest
        composer-deps-source:
          - dist
          - source
        include:
          - php-versions: '8.0'
            composer-versions: composer:v2 
            allow-to-fail: true

    steps:
    - uses: actions/checkout@v2

    - name: Install PHP ${{ matrix.php-versions }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        tools: ${{ matrix.composer-versions }}

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer update --prefer-${{ matrix.composer-deps }} --prefer-${{ matrix.composer-deps-source }} --no-interaction
      
    - name: Run Unit Tests
      run: vendor/bin/phpunit

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
